---
- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    COMMON_ENABLE_DATADOG: True
    COMMON_ENABLE_SPLUNKFORWARDER: True
    COMMON_SECURITY_UPDATES: yes
    SECURITY_UPGRADE_ON_ANSIBLE: true

    SPLUNKFORWARDER_LOG_ITEMS:
      - source: '/var/lib/jenkins/jobs/*/builds/*/junitResult.xml'
        recursive: true
        index: 'testeng'
        sourcetype: junit
        followSymlink: false
        crcSalt: '<SOURCE>'

      - source: '/var/lib/jenkins/jobs/*/builds/*/build.xml'
        index: 'testeng'
        recursive: true
        sourcetype: build_result
        followSymlink: false
        crcSalt: '<SOURCE>'
        blacklist: '(((\.(gz))|\d)$)|(.*seed.*)'

      - source: '/var/lib/jenkins/jobs/*/builds/*/log'
        index: 'testeng'
        recursive: true
        sourcetype: build_log
        followSymlink: false
        crcSalt: '<SOURCE>'
        blacklist: '(((\.(gz))|\d)$)|(.*seed.*)'

      - source: '/var/lib/jenkins/jobs/*/builds/*/archive/test_root/log/timing.*.log'
        index: 'testeng'
        sourcetype: 'json_timing_log'
        followSymlink: false

      - source: '/var/lib/jenkins/jobs/*/builds/*/archive/sitespeed-result/*/data/result.json'
        index: 'testeng'
        recursive: true
        sourcetype: sitespeed_result
        followSymlink: false

      - source: '/var/log/jenkins/jenkins.log'
        index: 'testeng'
        recursive: false
        followSymlink: false

  roles:
    - aws
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - jenkins_build

    # run just the splunkforwarder role by using '--tags "splunkonly"'
    # e.g. ansible-playbook jenkins_testeng_master.yml -i inventory.ini --tags "splunkonly" -vvvv
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
      tags: splunkonly
      become: True
